openapi: "3.0.3"
info:
  title: API Users
  version: "1.0"
paths:
  /products/json:
    get:
      summary: Obtienes todos los productos
      tags:
        - products
      parameters:
        - name: token_key
          in: header
          description: ''
          required: true
          schema:
            type: string

      responses:
        "200":
          description: Todos los productos han sido obtenidos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
  
  /products:
    post:
      tags:
        - products
      summary: Add a new product to the store
      description: Add a new product to the store
      operationId: addProduct
      requestBody:
        description: Create a new product in the store
        content:
          application/json:
            schema:
              $ref: '#/components/body/Product'
          application/xml:
            schema:
              $ref: '#/components/body/Product'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/body/Product'
        required: true
      parameters:
        - name: token_key
          in: header
          description: ''
          required: true
          schema:
            type: string

      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/responses/Create'          
            application/xml:
              schema:
                $ref: '#/responses/Create'
        '400':
          description: Invalid input
        '500':
          description: Internal Server Error
  /products/{productId}:
    get:
      tags:
        - products
      summary: Find product by ID
      description: Returns a product
      operationId: getProductById
      parameters:
        - name: productId
          in: path
          description: ID of product to return
          required: true
          schema:
            type: string
            
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found
        '500':
          description: Internal Server Error
    put:
      tags:
        - products
      summary: Update an existing product
      description: Update an existing product by Id
      operationId: updateProduct
      requestBody:
        description: Update an existent product in the store
        content:
          application/json:
            schema:
              $ref: '#/components/body/Product'
          application/xml:
            schema:
              $ref: '#/components/body/Product'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/body/Product'
        required: true
      parameters:
        - name: token_key
          in: header
          description: ''
          required: true
          schema:
            type: string
        - name: productId
          in: path
          description: ID of product to return
          required: true
          schema:
            type: string

      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/body/Product'          
            application/xml:
              schema:
                $ref: '#/components/body/Product'
        '400':
          description: Invalid ID supplied
        '404':
          description: Product not found
        '500':
          description: Internal Server Error
  
    delete:
      tags:
        - products
      summary: Deletes a product
      description: delete a product
      operationId: deleteProduct
      parameters:
        - name: token_key
          in: header
          description: ''
          required: true
          schema:
            type: string
        - name: productId
          in: path
          description: Product id to delete
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/body/Product'          
            application/xml:
              schema:
                $ref: '#/components/body/Product'
        '400':
          description: Invalid pet value
        '500':
          description: Internal Server Error

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: string
          description: Id de mongo
        name:
          type: string
          description: Nombre del producto
        description:
          type: string
          description: Descripcion del producto
        price:
          type: number
          description: Precio del producto
        thumbnail:
          type: string
          description: Imagen del producto
        stock:
          type: number
          description: Stock del producto
        status:
          type: boolean
          description: Puede ser true o false
        createAt:
          type: date
          description: Creacion del producto
        updateAt:
          type: date
          description: Actualizacion del producto
        deleteAt:
          type: date
          description: Eliminacion del producto
      example:
        _id: ObjectId("hydas78dyas8ndhas8")
        name: Iphone 15
        description: The best mobile in the world
        price: 999
        thumbnail: iphone15.png
        stock: 15
        status: false
        createAt: 09-15-22
        updateAt: 22-15-22
        deleteAt: 12-12-22
  body:
    Product:
      example:
        name: iphone 15
        description: The best mobile in the world
        price: 999
        thumbnail: iphone15.png
        stock: 15


responses:
    Create:
      example:
        status: success
        messagge: new product created
    Delete:
      example:
        status: success
        messagge:  Product deleted
    Update:
      example:
        status: success
        messagge:  Product updated
        